# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ....
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

mx = 4 * 10**6
arr = []
while True:
    if arr == []:
        arr.append(1)
        arr.append(2)
    if arr[-1] < mx:
        sm = arr[-1] + arr[-2]
        arr.append(sm)
        sm = 0
    else:
        break

add = 0
for i in arr:
    if i%2 == 0:
        add = add + i

print('The sum of the even-valued terms in the Fibonacci sequence not exceeding four million is:', add)